---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: all
  remote_user: ec2-user
  become: root
  become_method: sudo
  environment:
    http_proxy: http://172.31.13.6:3128
    https_proxy: http://172.31.13.6:3128
    no_proxy: 169.254.169.254

  roles:
    - selinux
    - tomcat
